### ISSUE TITLE
Manque le fichier de style logicpuzzle.sty

### ISSUE THREAD

**Issue by Dalker** [redelmann/gyminf-informatique-theorique#3]
Pour compiler `exercices/1_calcul_des_propositions.tex`, on a besoin de ce fichier de style, mais il ne fait pas partie du _repository_.

Message d'erreur lors de la compilation:

> ! LaTeX Error: File `logicpuzzle.sty' not found.
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: sty

**Comment by redelmann** [comment]
Le package était inclus dans ma distribution de LaTeX. J'ai ajouté le fichier manuellement. Est-ce que cela résout le problème de compilation ? Merci !

**Comment by redelmann** [comment]
J'ai ajouté les fichiers .sty manquants. Les fichiers sont aussi disponibles via texlive-games. Merci @Dalker !
