### ISSUE TITLE
Mon LaTeX ne reconnait pas le petit cercle U+B0

### ISSUE THREAD

**Issue by danjane** [redelmann/gyminf-informatique-theorique#9]
Je n'arrive pas à compiler LaTeX avec le symbole " ° ", par exemple dans le titre

Réponses à la série d'exercices n°1

Le message d'erreure :
! Package inputenc Error: Unicode character ° (U+B0)
(inputenc)                not set up for use with LaTeX.

**Comment by MurieleJ** [comment]
Désolée Dan,  je tape en latex directement  en ligne depuis mon mac et je ne compile pas. Tu peux essayer, avec le package mathabx et la commande \degree ou avec le package textcomp et la commande \textdegree

**Comment by redelmann** [comment]
J'ai ajouté des packages pour le support d'UTF-8. Est-ce que ça résout le problème rencontré ?

**Comment by Dalker** [comment]
Il me semble que `\usepackage[T1]{fontenc}` évite ce souci (que j'avais aussi). Quand on compile avec `lualatex` et que `babel[francais]` est présent mais pas `fontenc`, il apparaît comme suggestion dans les Warnings de compilation, et ça semble résoudre le problème.

**Comment by Dalker** [comment]
Il y a une explication assez complète sur "comment bien gérer les accents/utf8 en LaTeX"  [ici](https://blog.dorian-depriester.fr/latex/mais-a-quoi-bon-servent-les-packages-fontenc-et-inputenc)

**Comment by redelmann** [comment]
Merci @Dalker ! J'ai mis en place la solution suggérée. @danjane est-ce que ça résout ton problème ?

**Comment by danjane** [comment]
Merci aussi @Dalker ! Maintenant si je compile avec lualatex (et plus avec pdflatex) il marche très bien.
